# Linux ARM64 - native cross-compilation
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Windows x86_64 GNU - native mingw-w64
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

# Other targets handled by cross tool via Docker:
# - x86_64-apple-darwin
# - aarch64-apple-darwin